//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaloguj.
        /// </summary>
        public static string S1 {
            get {
                return ResourceManager.GetString("S1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wymagana liczba znaków nowego hasła to.
        /// </summary>
        public static string S10 {
            get {
                return ResourceManager.GetString("S10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szczegóły nadawcy.
        /// </summary>
        public static string S100 {
            get {
                return ResourceManager.GetString("S100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane szczegółowe nadawcy.
        /// </summary>
        public static string S101 {
            get {
                return ResourceManager.GetString("S101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pogląd skanu.
        /// </summary>
        public static string S102 {
            get {
                return ResourceManager.GetString("S102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak danych spełniających podane kryteria.
        /// </summary>
        public static string S103 {
            get {
                return ResourceManager.GetString("S103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten dokument nie był jeszcze edytowany.
        /// </summary>
        public static string S104 {
            get {
                return ResourceManager.GetString("S104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podgląd.
        /// </summary>
        public static string S105 {
            get {
                return ResourceManager.GetString("S105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmiana hasła nie powiodła się. Popraw błędy i spróbuj ponownie.
        /// </summary>
        public static string S106 {
            get {
                return ResourceManager.GetString("S106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twoje hasło zostało pomyślnie zmienione.
        /// </summary>
        public static string S107 {
            get {
                return ResourceManager.GetString("S107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logowanie nie powiodło się. Popraw błędy i spróbuj ponownie.
        /// </summary>
        public static string S108 {
            get {
                return ResourceManager.GetString("S108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten skan posiada wersje.
        /// </summary>
        public static string S109 {
            get {
                return ResourceManager.GetString("S109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obecne hasło.
        /// </summary>
        public static string S11 {
            get {
                return ResourceManager.GetString("S11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podgląd skanów dokumentu.
        /// </summary>
        public static string S110 {
            get {
                return ResourceManager.GetString("S110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokalizacja wyszukiwanej frazy.
        /// </summary>
        public static string S111 {
            get {
                return ResourceManager.GetString("S111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ładowanie plików.
        /// </summary>
        public static string S112 {
            get {
                return ResourceManager.GetString("S112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to podgląd pliku.
        /// </summary>
        public static string S113 {
            get {
                return ResourceManager.GetString("S113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie udało się usunąć skanu z kosza..
        /// </summary>
        public static string S114 {
            get {
                return ResourceManager.GetString("S114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przeglądaj wersje.
        /// </summary>
        public static string S115 {
            get {
                return ResourceManager.GetString("S115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poprzednia.
        /// </summary>
        public static string S116 {
            get {
                return ResourceManager.GetString("S116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Następna.
        /// </summary>
        public static string S117 {
            get {
                return ResourceManager.GetString("S117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strona główna aplikacji eArchiver.
        /// </summary>
        public static string S118 {
            get {
                return ResourceManager.GetString("S118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmiana hasła.
        /// </summary>
        public static string S119 {
            get {
                return ResourceManager.GetString("S119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowe hasło.
        /// </summary>
        public static string S12 {
            get {
                return ResourceManager.GetString("S12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - wybierz -.
        /// </summary>
        public static string S120 {
            get {
                return ResourceManager.GetString("S120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nadawca.
        /// </summary>
        public static string S121 {
            get {
                return ResourceManager.GetString("S121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edycja nadawcy.
        /// </summary>
        public static string S122 {
            get {
                return ResourceManager.GetString("S122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobierz oznakowany.
        /// </summary>
        public static string S123 {
            get {
                return ResourceManager.GetString("S123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podziel plik.
        /// </summary>
        public static string S124 {
            get {
                return ResourceManager.GetString("S124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powtórz nowe hasło.
        /// </summary>
        public static string S13 {
            get {
                return ResourceManager.GetString("S13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmień.
        /// </summary>
        public static string S14 {
            get {
                return ResourceManager.GetString("S14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strona główna.
        /// </summary>
        public static string S15 {
            get {
                return ResourceManager.GetString("S15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skany.
        /// </summary>
        public static string S16 {
            get {
                return ResourceManager.GetString("S16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dokumenty.
        /// </summary>
        public static string S17 {
            get {
                return ResourceManager.GetString("S17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustawienia.
        /// </summary>
        public static string S18 {
            get {
                return ResourceManager.GetString("S18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownicy.
        /// </summary>
        public static string S19 {
            get {
                return ResourceManager.GetString("S19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string S2 {
            get {
                return ResourceManager.GetString("S2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dostępne skany.
        /// </summary>
        public static string S20 {
            get {
                return ResourceManager.GetString("S20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobierz.
        /// </summary>
        public static string S21 {
            get {
                return ResourceManager.GetString("S21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odśwież.
        /// </summary>
        public static string S22 {
            get {
                return ResourceManager.GetString("S22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj z dysku.
        /// </summary>
        public static string S23 {
            get {
                return ResourceManager.GetString("S23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kosz skanów.
        /// </summary>
        public static string S24 {
            get {
                return ResourceManager.GetString("S24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do kosza.
        /// </summary>
        public static string S25 {
            get {
                return ResourceManager.GetString("S25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaznacz.
        /// </summary>
        public static string S26 {
            get {
                return ResourceManager.GetString("S26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odznacz.
        /// </summary>
        public static string S27 {
            get {
                return ResourceManager.GetString("S27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane podstawowe.
        /// </summary>
        public static string S28 {
            get {
                return ResourceManager.GetString("S28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Znak pisma.
        /// </summary>
        public static string S29 {
            get {
                return ResourceManager.GetString("S29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logowanie.
        /// </summary>
        public static string S3 {
            get {
                return ResourceManager.GetString("S3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teczka.
        /// </summary>
        public static string S30 {
            get {
                return ResourceManager.GetString("S30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data pisma.
        /// </summary>
        public static string S31 {
            get {
                return ResourceManager.GetString("S31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Słowa kluczowe.
        /// </summary>
        public static string S32 {
            get {
                return ResourceManager.GetString("S32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorie.
        /// </summary>
        public static string S33 {
            get {
                return ResourceManager.GetString("S33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rodzaj.
        /// </summary>
        public static string S34 {
            get {
                return ResourceManager.GetString("S34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sklep.
        /// </summary>
        public static string S35 {
            get {
                return ResourceManager.GetString("S35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane dodatkowe.
        /// </summary>
        public static string S36 {
            get {
                return ResourceManager.GetString("S36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nadawcy.
        /// </summary>
        public static string S37 {
            get {
                return ResourceManager.GetString("S37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista dostępnych.
        /// </summary>
        public static string S38 {
            get {
                return ResourceManager.GetString("S38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj.
        /// </summary>
        public static string S39 {
            get {
                return ResourceManager.GetString("S39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło.
        /// </summary>
        public static string S4 {
            get {
                return ResourceManager.GetString("S4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń.
        /// </summary>
        public static string S40 {
            get {
                return ResourceManager.GetString("S40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodatkowe informacje.
        /// </summary>
        public static string S41 {
            get {
                return ResourceManager.GetString("S41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Załatwione.
        /// </summary>
        public static string S42 {
            get {
                return ResourceManager.GetString("S42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowy nadawca.
        /// </summary>
        public static string S43 {
            get {
                return ResourceManager.GetString("S43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imię.
        /// </summary>
        public static string S44 {
            get {
                return ResourceManager.GetString("S44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwisko.
        /// </summary>
        public static string S45 {
            get {
                return ResourceManager.GetString("S45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma.
        /// </summary>
        public static string S46 {
            get {
                return ResourceManager.GetString("S46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIP.
        /// </summary>
        public static string S47 {
            get {
                return ResourceManager.GetString("S47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt.
        /// </summary>
        public static string S48 {
            get {
                return ResourceManager.GetString("S48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres e-mail.
        /// </summary>
        public static string S49 {
            get {
                return ResourceManager.GetString("S49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pamiętaj mnie.
        /// </summary>
        public static string S5 {
            get {
                return ResourceManager.GetString("S5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon domowy.
        /// </summary>
        public static string S50 {
            get {
                return ResourceManager.GetString("S50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon służbowy.
        /// </summary>
        public static string S51 {
            get {
                return ResourceManager.GetString("S51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres strony w sieci Web.
        /// </summary>
        public static string S52 {
            get {
                return ResourceManager.GetString("S52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon komórkowy.
        /// </summary>
        public static string S53 {
            get {
                return ResourceManager.GetString("S53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faks służbowy.
        /// </summary>
        public static string S54 {
            get {
                return ResourceManager.GetString("S54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        public static string S55 {
            get {
                return ResourceManager.GetString("S55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulica.
        /// </summary>
        public static string S56 {
            get {
                return ResourceManager.GetString("S56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budynek.
        /// </summary>
        public static string S57 {
            get {
                return ResourceManager.GetString("S57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokal.
        /// </summary>
        public static string S58 {
            get {
                return ResourceManager.GetString("S58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod pocztowy.
        /// </summary>
        public static string S59 {
            get {
                return ResourceManager.GetString("S59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witaj.
        /// </summary>
        public static string S6 {
            get {
                return ResourceManager.GetString("S6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miejscowość.
        /// </summary>
        public static string S60 {
            get {
                return ResourceManager.GetString("S60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poczta.
        /// </summary>
        public static string S61 {
            get {
                return ResourceManager.GetString("S61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inne.
        /// </summary>
        public static string S62 {
            get {
                return ResourceManager.GetString("S62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notatki.
        /// </summary>
        public static string S63 {
            get {
                return ResourceManager.GetString("S63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz.
        /// </summary>
        public static string S64 {
            get {
                return ResourceManager.GetString("S64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anuluj.
        /// </summary>
        public static string S65 {
            get {
                return ResourceManager.GetString("S65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podgląd ostatnio zaznaczonego skanu.
        /// </summary>
        public static string S66 {
            get {
                return ResourceManager.GetString("S66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utwórz dokument.
        /// </summary>
        public static string S67 {
            get {
                return ResourceManager.GetString("S67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyczyść formularz.
        /// </summary>
        public static string S68 {
            get {
                return ResourceManager.GetString("S68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przejdź do ostatnio utworzonego dokumentu.
        /// </summary>
        public static string S69 {
            get {
                return ResourceManager.GetString("S69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmień hasło.
        /// </summary>
        public static string S7 {
            get {
                return ResourceManager.GetString("S7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj skan.
        /// </summary>
        public static string S70 {
            get {
                return ResourceManager.GetString("S70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz plik który chcesz dodać do listy.
        /// </summary>
        public static string S71 {
            get {
                return ResourceManager.GetString("S71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powrót do listy skanów.
        /// </summary>
        public static string S72 {
            get {
                return ResourceManager.GetString("S72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przywróć do listy skanów.
        /// </summary>
        public static string S73 {
            get {
                return ResourceManager.GetString("S73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń z kosza.
        /// </summary>
        public static string S74 {
            get {
                return ResourceManager.GetString("S74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobrany.
        /// </summary>
        public static string S75 {
            get {
                return ResourceManager.GetString("S75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to godz.
        /// </summary>
        public static string S76 {
            get {
                return ResourceManager.GetString("S76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametry wyszukiwania.
        /// </summary>
        public static string S77 {
            get {
                return ResourceManager.GetString("S77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data utworzenia [od] -[do].
        /// </summary>
        public static string S78 {
            get {
                return ResourceManager.GetString("S78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data pisma [od] - [do].
        /// </summary>
        public static string S79 {
            get {
                return ResourceManager.GetString("S79", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyloguj.
        /// </summary>
        public static string S8 {
            get {
                return ResourceManager.GetString("S8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fraza w treści.
        /// </summary>
        public static string S80 {
            get {
                return ResourceManager.GetString("S80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba elementów na stronie.
        /// </summary>
        public static string S81 {
            get {
                return ResourceManager.GetString("S81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyszukaj dokument.
        /// </summary>
        public static string S82 {
            get {
                return ResourceManager.GetString("S82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyniki wyszukiwania.
        /// </summary>
        public static string S83 {
            get {
                return ResourceManager.GetString("S83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data utworzenia.
        /// </summary>
        public static string S84 {
            get {
                return ResourceManager.GetString("S84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otwórz.
        /// </summary>
        public static string S85 {
            get {
                return ResourceManager.GetString("S85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strona.
        /// </summary>
        public static string S86 {
            get {
                return ResourceManager.GetString("S86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powrót do wyników wyszukiwania.
        /// </summary>
        public static string S87 {
            get {
                return ResourceManager.GetString("S87", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj dokument.
        /// </summary>
        public static string S88 {
            get {
                return ResourceManager.GetString("S88", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autor.
        /// </summary>
        public static string S89 {
            get {
                return ResourceManager.GetString("S89", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klient.
        /// </summary>
        public static string S9 {
            get {
                return ResourceManager.GetString("S9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historia edycji.
        /// </summary>
        public static string S90 {
            get {
                return ResourceManager.GetString("S90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane dokumentu.
        /// </summary>
        public static string S91 {
            get {
                return ResourceManager.GetString("S91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj skan z listy.
        /// </summary>
        public static string S92 {
            get {
                return ResourceManager.GetString("S92", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj skan z dysku.
        /// </summary>
        public static string S93 {
            get {
                return ResourceManager.GetString("S93", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj wersję z listy.
        /// </summary>
        public static string S94 {
            get {
                return ResourceManager.GetString("S94", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj wersję z dysku.
        /// </summary>
        public static string S95 {
            get {
                return ResourceManager.GetString("S95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz skany.
        /// </summary>
        public static string S96 {
            get {
                return ResourceManager.GetString("S96", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historia zmian dokumentu.
        /// </summary>
        public static string S97 {
            get {
                return ResourceManager.GetString("S97", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data zmiany.
        /// </summary>
        public static string S98 {
            get {
                return ResourceManager.GetString("S98", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytor.
        /// </summary>
        public static string S99 {
            get {
                return ResourceManager.GetString("S99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podana wartość musi być numeryczna.
        /// </summary>
        public static string ValidationFieldMustBeNumeric {
            get {
                return ResourceManager.GetString("ValidationFieldMustBeNumeric", resourceCulture);
            }
        }
    }
}
